export default function(){
  this.transition(
  	this.toRoute('index'),
  	this.use('toDown')
  );
  this.transition(
  	this.toRoute('synthese'),
  	this.use('toDown')
  );
  this.transition(
  	this.toRoute('daily-report'),
  	this.use('toDown')
  );
  this.transition(
  	this.toRoute('profile'),
  	this.use('toDown')
  );
  this.transition(
  	this.toRoute('cycle'),
  	this.use('toDown')
  );
  this.transition(
    this.fromRoute('cycle'),
    this.toRoute('temperatures'),
    this.use('toUp'),
    this.reverse('toDown')
  );
  this.transition(
    this.fromRoute('cycle'),
    this.toRoute('periods'),
    this.use('toUp'),
    this.reverse('toDown')
  );
  this.transition(
    this.fromRoute('cycle'),
    this.toRoute('cervix-feelings'),
    this.use('toUp'),
    this.reverse('toDown')
  );
  this.transition(
    this.fromRoute('cycle'),
    this.toRoute('mucus-samples'),
    this.use('toUp'),
    this.reverse('toDown')
  );
  this.transition(
    this.fromRoute("temperatures"),
  	this.toRoute('temperature'),
  	this.use('toLeft'),
  	this.reverse('toRight')
  );
  this.transition(
    this.fromRoute('periods'),
  	this.toRoute('period'),
  	this.use('toLeft'),
  	this.reverse('toRight')
  );
  this.transition(
    this.fromRoute('mucus-samples'),
  	this.toRoute('mucus-sample'),
  	this.use('toLeft'),
  	this.reverse('toRight')
  );
  this.transition(
    this.fromRoute('cervix-feelings'),
  	this.toRoute('cervix-feeling'),
  	this.use('toLeft'),
  	this.reverse('toRight')
  );

  this.transition(
    this.fromRoute("cervix-feeling"),
    this.toRoute('temperature'),
    this.use('toRight')
  );
  this.transition(
    this.fromRoute("period"),
    this.toRoute('temperature'),
    this.use('toRight')
  );
  this.transition(
    this.fromRoute("mucus-sample"),
    this.toRoute('temperature'),
    this.use('toRight')
  );

  this.transition(
    this.fromRoute("temperature"),
    this.toRoute('cervix-feeling'),
    this.use('toLeft')
  );
  this.transition(
    this.fromRoute("period"),
    this.toRoute('cervix-feeling'),
    this.use('toRight')
  );
  this.transition(
    this.fromRoute("mucus-sample"),
    this.toRoute('cervix-feeling'),
    this.use('toLeft')
  );

  this.transition(
    this.fromRoute("temperature"),
    this.toRoute('mucus-sample'),
    this.use('toLeft')
  );
  this.transition(
    this.fromRoute("period"),
    this.toRoute('mucus-sample'),
    this.use('toRight')
  );
  this.transition(
    this.fromRoute("cervix-feeling"),
    this.toRoute('mucus-sample'),
    this.use('toRight')
  );

  this.transition(
    this.fromRoute("cervix-feeling"),
    this.toRoute('period'),
    this.use('toLeft')
  );
  this.transition(
    this.fromRoute("temperature"),
    this.toRoute('period'),
    this.use('toLeft')
  );
  this.transition(
    this.fromRoute("mucus-sample"),
    this.toRoute('period'),
    this.use('toLeft')
  );
}